"""Builder de prompts para o Claude gerar RunnerConfigs."""

from __future__ import annotations

from pathlib import Path

from ..models import Workspace


def pending_runner_path(workspace: Workspace) -> Path:
    """Caminho onde o Claude deve salvar o JSON gerado.

    O botão 'Recarregar runners' da aba Runners lê desse arquivo e
    importa via runners_io.import_runners.
    """
    return (
        Path.home()
        / ".config"
        / "claude-workspaces"
        / "runner-drafts"
        / f"{workspace.id}.json"
    )


def build_generate_prompt(
    workspace: Workspace, hint: str = "", spec_path: str | Path | None = None
) -> str:
    folders = "\n".join(f"  - {f}" for f in workspace.folders) or "  (sem pastas)"
    hint_block = f"\nHint do usuário: {hint}\n" if hint.strip() else ""
    out_path = pending_runner_path(workspace)
    spec_ref = (
        f"`{spec_path}` (caminho absoluto — disponível via --add-dir)"
        if spec_path
        else "`docs/runners-spec.md` deste repositório (claude-workspaces)"
    )
    return (
        f"Leia {spec_ref} e "
        f"gere a configuração de um Runner para o workspace abaixo.\n\n"
        f"Workspace: {workspace.name}\n"
        f"Pastas:\n{folders}\n"
        f"{hint_block}\n"
        "=== INSTRUÇÕES DE INVESTIGAÇÃO (obrigatórias) ===\n\n"
        "NÃO gere comandos genéricos. NÃO chute. Você DEVE inspecionar cada "
        "pasta do workspace ANTES de propor qualquer comando. O comando "
        "correto está sempre nos arquivos de configuração — extraia de lá.\n\n"
        "Passo 1 — Liste a raiz de cada pasta do workspace:\n"
        "  Use Glob/LS na raiz pra identificar o stack (presença de "
        "`package.json`, `pom.xml`, `build.gradle`, `pyproject.toml`, "
        "`Cargo.toml`, `go.mod`, `Gemfile`, `composer.json`, `Makefile`, "
        "`docker-compose.yml`, `Dockerfile`, `.nvmrc`, `.tool-versions`, "
        "`.python-version`, `mise.toml`, `asdf` config, `README.md`).\n\n"
        "Passo 2 — Leia os arquivos de manifest com Read e extraia o "
        "comando real. Regras por stack:\n\n"
        "  NODE/JS (package.json):\n"
        "    - Abra `scripts` e procure por `dev` > `start` > `serve` (nessa "
        "ordem de preferência pra ambiente local). Se houver `dev:watch`, "
        "`dev:web`, etc., prefira o mais específico ao stack do projeto.\n"
        "    - Detecte o package manager pela presença de "
        "`pnpm-lock.yaml` (pnpm), `yarn.lock` (yarn), `bun.lockb` (bun), "
        "senão `package-lock.json` (npm). Use `pnpm run X` / `yarn X` / "
        "`bun run X` / `npm run X` consistente com o lockfile.\n"
        "    - Se o framework é Next/Vite/Nuxt/Remix/Astro, verifique se há "
        "`turbo.json` ou monorepo (`pnpm-workspace.yaml`, `nx.json`) — nesses "
        "casos o comando pode ser `pnpm --filter <pkg> dev` ou "
        "`turbo run dev --filter=<pkg>`.\n"
        "    - Se houver `.nvmrc`, prefira `nvm use && pnpm dev` quando o "
        "usuário usa nvm; senão deixe o comando direto.\n\n"
        "  JAVA (pom.xml / build.gradle):\n"
        "    - Maven: procure plugins `spring-boot-maven-plugin` "
        "(→ `mvn spring-boot:run`), `tomcat7-maven-plugin` "
        "(→ `mvn tomcat7:run`), `jetty-maven-plugin` (→ `mvn jetty:run`), "
        "`cargo-maven2-plugin` (Liferay → `mvn cargo:run`). Se for `war` sem "
        "plugin embutido, o runner provavelmente é deploy num app server "
        "externo (Glassfish/Tomcat/WildFly) — use os scripts "
        "`asadmin`/`catalina.sh`/`standalone.sh` com paths absolutos.\n"
        "    - Gradle: procure tasks `bootRun`, `run`, `appRun`. Use "
        "`./gradlew bootRun` se houver wrapper.\n"
        "    - Versão do Java: leia `<maven.compiler.source>`, "
        "`<java.version>`, `sourceCompatibility`. Se a hint mencionar "
        "múltiplas versões (ex: \"java 8 e java 25\"), case CADA pasta com "
        "sua versão e prefixe `JAVA_HOME=/usr/lib/jvm/java-X-openjdk PATH=$JAVA_HOME/bin:$PATH` no comando.\n\n"
        "  PYTHON (pyproject.toml / requirements.txt / manage.py):\n"
        "    - Django: se existe `manage.py`, use "
        "`python manage.py runserver 0.0.0.0:8000`.\n"
        "    - FastAPI/Flask: procure em `pyproject.toml` por scripts "
        "`[project.scripts]` ou `[tool.poetry.scripts]`. Se houver "
        "`uvicorn`/`gunicorn` nas deps, infira o app path (`module:app`) "
        "de `main.py`/`app.py`.\n"
        "    - Prefira `.venv/bin/python` se houver venv; senão `python` ou "
        "`uv run` (se `uv.lock` existe).\n\n"
        "  GO / RUST / RUBY / PHP:\n"
        "    - Go: `go run ./cmd/<bin>` ou `go run main.go` — confira a "
        "estrutura.\n"
        "    - Rust: `cargo run` (lê `Cargo.toml [[bin]]` se tiver vários).\n"
        "    - Ruby/Rails: `bundle exec rails server` se `config.ru` + "
        "`Gemfile` com rails.\n"
        "    - PHP/Laravel: `php artisan serve` se `artisan` na raiz.\n\n"
        "  DOCKER:\n"
        "    - Se houver `docker-compose.yml` e o projeto roda primário "
        "via container, use `docker compose up` como start_cmd e "
        "`docker compose down` como stop_cmd.\n\n"
        "Passo 2.5 — VERIFIQUE que o runtime/toolchain necessário está "
        "instalado e descubra o caminho real. Use Bash pra checar:\n"
        "  - Node:    `node -v` e `which node` (e `pnpm -v`/`yarn -v`/"
        "`bun -v`/`npm -v` conforme o lockfile)\n"
        "  - Java:    `java -version` (stderr), `which java`, "
        "`ls /usr/lib/jvm 2>/dev/null` pra listar JDKs disponíveis. "
        "Se a hint exige uma versão específica, escolha o JAVA_HOME "
        "que casa (ex: `/usr/lib/jvm/java-8-openjdk`).\n"
        "  - Python:  `python3 -V`, `which python3`, e `ls .venv/bin/python "
        "2>/dev/null` pra venv local; `uv --version` se `uv.lock` existe.\n"
        "  - Go:      `go version`\n"
        "  - Rust:    `cargo --version`\n"
        "  - .NET:    `dotnet --version` e `dotnet --list-sdks`\n"
        "  - Ruby:    `ruby -v`, `bundle -v`\n"
        "  - PHP:     `php -v`, `composer --version`\n"
        "  - Docker:  `docker --version` e `docker compose version`\n"
        "  - App servers externos: `which asadmin` / "
        "`ls /opt/glassfish*/bin/asadmin 2>/dev/null`, "
        "`which catalina.sh` / `ls /opt/tomcat*/bin 2>/dev/null`, "
        "`ls /opt/wildfly*/bin/standalone.sh 2>/dev/null`.\n\n"
        "Se a ferramenta NÃO estiver instalada ou a versão exigida não "
        "existir, NÃO invente — gere o runner com `enabled: false` e "
        "inclua no `name` um sufixo `(faltando: <tool>)` para sinalizar. "
        "Mencione no relato final o que está faltando instalar.\n\n"
        "Se o caminho do binário/runtime não está no PATH default (ex: "
        "Java 8 instalado em `/usr/lib/jvm/java-8-openjdk`), prefixe "
        "`JAVA_HOME=... PATH=$JAVA_HOME/bin:$PATH` no start_cmd em vez "
        "de assumir PATH global.\n\n"
        "Passo 3 — Determine `cwd`. Por padrão é a pasta do workspace que "
        "tem o manifest. Em monorepo, pode ser uma subpasta (`apps/web`, "
        "`packages/api`).\n\n"
        "Passo 4 — Para stop_cmd/restart_cmd:\n"
        "  - Processos foreground (npm run dev, mvn spring-boot:run): "
        "deixe stop_cmd vazio (o runner manda SIGTERM) e restart_cmd "
        "vazio (stop + start padrão).\n"
        "  - Servidores que daemonizam (Glassfish, Tomcat externo, "
        "WildFly): use os scripts asadmin/catalina/standalone explícitos.\n\n"
        "=== FORMATO DE SAÍDA ===\n\n"
        "Gere o JSON do RunnerConfig com os campos: name, start_cmd, "
        "stop_cmd, restart_cmd, cwd (opcional), enabled. Nomeie cada runner "
        "de forma curta e específica (`web`, `api`, `glassfish-ogpms`, "
        "`worker-emails`) — evite nomes genéricos como \"runner\" ou "
        "\"app\".\n\n"
        f"IMPORTANTE — salve o resultado no arquivo:\n  {out_path}\n\n"
        "no formato esperado pelo import (envelope com a chave `runners`, "
        "uma lista):\n"
        '  {"runners": [ { ...config... } ]}\n\n'
        "Crie diretórios pai se necessário (mkdir -p). Depois de salvar, "
        "informe ao usuário:\n"
        "  1) Quais arquivos você leu e o que extraiu de cada um (ex: "
        "\"li package.json em apps/web → script `dev` = `next dev`\").\n"
        "  2) Que ele deve clicar em **↻ Recarregar runners** no header "
        "da aba Runners do claude-workspaces para importar."
    )
